### ISSUE TITLE
log Class

### ISSUE THREAD

**Issue by test030-sudo** [RoySRC/CPPLOGGER#47]
Hey, is it possible to log a class?

I have e.g. this class:
`class MyClass {
private:
    int value;

public:
    MyClass(int v) : value(v) {}

    // Überladen des <<-Operators für MyClass
    friend std::ostream& operator<<(std::ostream& os, const MyClass& obj) {
        os << "MyClass(" << obj.value << ")";
        return os;
    }
};`

with the << operator overloaded.
But I can't log it e.g. with 
`MyClass my(22);
  logger_info("This is an test", my);`

**Comment by RoySRC** [comment]
Have you tried something like this:
```c++
class class_name {
    int a = 0;
    int b = 1;
    int c = 2;
public:
    string to_string() {
        using std::to_string;
        return logger_get_type(this) + " {\n a: " + 
                    to_string(a) + 
                    "\n b: " + 
                    to_string(b) + 
                    "\n c: " + 
                    to_string(c) + 
        "\n}";
    }
};

int main() {
    class_name instance;
    logger_info("This is a test %s", instance.to_string());
}
```
At this time the logger instance can only take string objects. I guess one could modify the logger function to take in any arbitrary types using template programming and `std::is_same` function. I haven't scoped out the changes yet, but it would probably require a rewrite of the library.

Note that `logger_get_type(...)` might not work if you are not using the GNU compiler toolchain. In such cases, I recommend replacing `logger_get_type(...)` with the name of the actual class.

**Comment by RoySRC** [comment]
@test030-sudo, did that solve your problem? If so, please let me know so I can close this issue.

**Comment by test030-sudo** [comment]
Thanks for the suggestion and anwser!
That solved my problem.

Sorry for the late reply.

P.s.: would it be possible to not include logger_init() in very class that imports another class with the CPPLOGGER included?
Because if I dont use logger_init() in those classes i get an error when compiling.

**Comment by RoySRC** [comment]
@test030-sudo, thanks for your reply. I think we should discuss this another issue with the exact compilation error message. Closing this issue now since the problem seems to be solved.
